### ISSUE TITLE
utf8 .conf file in release

### ISSUE THREAD

**Issue by 00dingens** [bitwalker/conform#101]
I can not reopen https://github.com/bitwalker/conform/issues/98 so I open a new issue.

on mix `conform.effective` utf8 encoded content in `.conf` file is supported,
but in a release it is still transcoded to latin-1.

**Comment by bitwalker** [comment]
Could you clarify what you mean? Which file has latin1 encoded content? Where are you noticing the problem?

**Comment by mgumz** [comment]
what @00dingens meant: using "mix conform.effective" shows "the right thing", but using *exrm* plus observing the values coming out of a .conf file in production still shows latin1.

we will recheck the issue, once we upgrade to the latest conform

**Comment by bitwalker** [comment]
This could likely be due to running the release in an environment where the locale Erlang is running under is `latin1`, rather than utf8, causing it to try and parse the `sys.config` as if it's `latin1`. I'm not aware of anything in exrm (or distillery) which transcode utf8 to latin1 though.
