### ISSUE TITLE
Why does schema map { _ , value } to { :atom , type(value) } ?

### ISSUE THREAD

**Issue by ftaebi** [bitwalker/conform#102]
Hi, in Conform.Schema.extract_datatype there is the line

    defp extract_datatype({_, v}), do: {:atom, extract_datatype(v)}

This causes a config line like 

    ttl: { 30, :days }

to generate the schema entry

    datatype: {:atom, :atom}

Which leads to an argument error in Conform.Translate.write_datatype/3 ( :erlang.atom_to_binary(30, :utf8) ) when you run configure.

My question is: what was the intention behind defp extract_datatype({_, v}), do: {:atom, extract_datatype(v)} ?

Why isn't there a

    defp extract_datatype({k, v}), do: {extract_datatype(k) , extract_datatype(v)}

?

It is clear to me that you cannot translate every exotic structure that someone wants to use and I think you wanted to make it possible to configure 

     book: { :name, "foo" }

which is a quite common thing. But why don't you explicitly check if the first field is an atom?

Thanks

**Comment by bitwalker** [comment]
This is indeed a mistake - the reason why that exists is to support keyword lists where the first element is always an atom, but you are absolutely correct that there is no reason why it couldn't extract the datatype of both elements. I'll get that fixed.
