### ISSUE TITLE
Make sorting of output config optional

### ISSUE THREAD

**Issue by mcelaney** [bitwalker/conform#104]
I have a project where we define config with a list. It looks something like this:

```
config :product_catalog, :frequently_purchased_with_recommendation_services, [
  {ProductCatalog.Recommendations.Service.Local, %{
    code: "<redacted>",
    customer_id: "<redacted>",
    page_template: "<redacted>",
    placeholder_name: "<redacted>",
    product_id_attribute_name: "<redacted>"
  }},
  {ProductCatalog.Recommendations.Service.Baynote, %{
    code: "<redacted>",
    customer_id: "<redacted>",
    page_template: "<redacted>",
    placeholder_name: "<redacted>",
    product_id_attribute_name: "<redacted>"
  }}
]
```

We (want to) do some stuff with the order of this list in the app - however conform seems to be chewing up the list when it translates the list to sys.config. To try to understand what is going on I changed the order of `configs/nested_list.exs` and then altered the assertions in ConfigTest to match my expectation (that the lists would be in the new order) and sure enough "can translate config.exs + schema + conf with nested lists to sys.config"

```

  1) test can translate config.exs + schema + conf with nested lists to sys.config (ConfigTest)
     test/config_test.exs:35
     Assertion with == failed
     code: [my_app: [rx_pattern: [~r"[A-Z]+"], sublist: [[opt1: "val3", opt2: "val-4"], [opt1: "val1", opt2: "val two"]]]] == sysconfig
     lhs:  [my_app: [rx_pattern: [~r/[A-Z]+/], sublist: [[opt1: "val3", opt2: "val-4"], [opt1: "val1", opt2: "val two"]]]]
     rhs:  [my_app: [rx_pattern: [~r/[A-Z]+/], sublist: [[opt1: "val1", opt2: "val two"], [opt1: "val3", opt2: "val-4"]]]]
     stacktrace:
       test/config_test.exs:41: (test)
```

I added a pull request with the failing spec (https://github.com/bitwalker/conform/pull/103) - I'm not entirely sure that is an example of my problem, however... Maybe I'm missing something?

**Comment by bitwalker** [comment]
The existing tests in `config_test.exs` already ensure the order is preserved all the way through. Can you provide me with a `config.exs`, `.conf`, and `.schema.exs` which I can use to reproduce the problem you're seeing?

**Comment by bitwalker** [comment]
The generated config is sorted for easy navigation, but I could make this an option probably. Thoughts?

**Comment by mcelaney** [comment]
@bitwalker Sorry - been trying to get ahead of myself enough to focus on this a bit.  I'll try to tease out a failing spec that demonstrates the problem we ran in to.

Optional sort would most likely solve my problem.  We ended up just committing a dirty, dirty, dirty hack in the meantime :P

**Comment by bitwalker** [comment]
Automatic sorting is now disabled except when pretty printing to the terminal :)

**Comment by mcelaney** [comment]
Thank you!
