### ISSUE TITLE
Possible to reload `.conf` file

### ISSUE THREAD

**Issue by JanStevens** [bitwalker/conform#105]
Is it possible to reload the conf file without restarting the app?
I found a very old repo that does it for conform + exrm: https://github.com/xerions/exrm_reload

**Comment by bitwalker** [comment]
There is nothing built in to conform which does this, though I could probably add a custom command to provide that capability in distillery.

**Comment by bitwalker** [comment]
As of the 2.2.0 tag of Conform, and master branch of Distillery, this is now possible via the `reload_config` command provided by the release boot script. Hex releases for both will be forthcoming, but I'm working on a few other changes before I do so.

**Comment by JanStevens** [comment]
Hello,

Any update on this? I noticed the `reload_config` command in Distillery and that seems to work but only for the `sys.config` file. It does not pickup changes in my `.conf` file.

**Comment by bitwalker** [comment]
It should be working now with the latest versions of Distillery/Conform.

**Comment by JanStevens** [comment]
Oke thanks but how? I tried `reload_config` but it only reload the sys.conf file, I only changed the `conf` file ofcourse.

Should I run something else before it so I generate a new sys.conf?

**Comment by bitwalker** [comment]
What versions of Distillery and Conform are you on? `reload_config` should do it, as it runs the pre_configure hooks that were added, and which Conform uses in place of pre_start.

**Comment by JanStevens** [comment]
```
"distillery": {:hex, :distillery, "1.2.2"
"conform": {:hex, :conform, "2.1.2",
```

**Comment by bitwalker** [comment]
Ok, I'll do some testing and follow up

**Comment by bitwalker** [comment]
Could you test with Conform 2.3? I'm unable to reproduce with 2.3. If you are still having an issue, can you describe how you are setting up your release and testing the reloading?

**Comment by JanStevens** [comment]
@bitwalker Thanks alot version 2.3 works perfectly!

**Comment by bitwalker** [comment]
Awesome!
