### ISSUE TITLE
sys.config generation broken in hooks

### ISSUE THREAD

**Issue by spscream** [bitwalker/conform#108]
I'm using conform the following way:
- starting conform pre_start hook in distillery
- starting migration command
- starting release

before 2.1.2 it worked, after 2.1.2 it is broken, since this commit: https://github.com/bitwalker/conform/commit/ab5bcccfe837306ffcbad1a8232db777e29a6167

since boot.eex always checking if release sys.config is different from sys.config from RELEASE_MUTABLE_DIR here: https://github.com/bitwalker/conform/commit/ab5bcccfe837306ffcbad1a8232db777e29a6167
it will always overwrite it to default sys.config passed with release on any bin/app args invocation.

it doesn't break release starting if only conform hook is executed, but anything crashes if any command  executed between conform hook and release actual start. So current solution for me was downgrade conform to 2.1.1

**Comment by bitwalker** [comment]
This turns out to be an issue in Distillery, which I've fixed in master. Can you give the fix a shot and let me know how it works out for you? In my tests it worked as expected.

**Comment by spscream** [comment]
@bitwalker and again it is broken for me on latest version of distillery and conform - sys.args rewritten by any command :( Sorry, but I don't have enough time now to reopen new issue, downgrading to old versions.

**Comment by bitwalker** [comment]
I recently encountered this in my own application, and found the problem - some of the logic around setting up vm.args and sys.config was not re-entrant, and would cause them to be set improperly. Give the latest versions of both conform and distillery a try and let me know if you are still running into problems.

**Comment by spscream** [comment]
@bitwalker thanks for update! 
Just returned from vacation and checked latest versions of distillery/conform and now it is working for me :)
