### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by mm-tfx** [bitwalker/conform#110]
Hi,
I have a problem with making conform to work with my Phoenix application.
I would like to have possibility to control port that Phoenix should use from env variable.
I have added conform into my mix.exs, I have run mix conform.new and mix conform.configure. I had run them with preceding MIX_ENV=prod to make it work.

Then was the part that was a bit difficult for me probably because I didn't understand something.
Anyhow I couldn't make it work.
Finally I copied app.conf and app.schema.exs into /app/rel/app/releases/0.0.1.
However when I tried to run my application it complained about missing conform file in the bin dir.
I have downloaded this file and copied it into bin dir.
Now it works as I expected.
PORT=1212 app console => server is started on port 1212
app console => server is started on random port (cowboy in Phoenix selects port itself.)

But I feel this is not proper and final solution and rather workaround. Could you please give me a little bit of clarification of things needed to make it work in a proper/nice way?

Thanks a lot.

**Comment by bitwalker** [comment]
Are you using distillery or exrm? If the latter, then you need to also include conform_exrm in your dependencies.

**Comment by mm-tfx** [comment]
I am using exrm. I'll try with conform_exrm.
I'll try with Distillery as well.

**Comment by bitwalker** [comment]
Would definitely recommend using Distillery if you have a choice - there is very little needed to migrate from exrm, and I'm no longer supporting exrm in any active capacity (I still merge PRs and the like, but those are few and far between these days).
