### ISSUE TITLE
cannot make empty list

### ISSUE THREAD

**Issue by nhalm2** [bitwalker/conform#111]
I'm having a really hard time trying to figure out how to make an empty list in version 2.1.2.  For instance, in your tests if I change `test/confs/complex_example.conf` so that it looks like this:
    some_val = foo

    sublist_example.opt1 = val1v
    sublist_example."opt-2" = val2

You end up with this:

    [my_app: [
      complex_another_list: ["$person": [age: nil], first: [username: "test_username1"]], 
      complex_list: ["$person": [age: 30, type: :undefined]], 
      some_val: :foo, 
      some_val2: 2.5, 
      sublist: ["opt-2": "val2", opt1:    "val1"]]]

What I am trying to do is to not have the defaults.  If I didn't set anything then the default it getting this `$person` and a keyword list.  I just want it to be:

    [my_app: [
      complex_another_list: [], 
      complex_list: [], 
      some_val: :foo, 
      sublist: ["opt-2": "val2", opt1:    "val1"]]]

I hope this makes sense.  I think I am basically looking for a way to make the default an empty list. I'd be happy to try and make this part of the library if it isn't possible currently.

**Comment by bitwalker** [comment]
You should just be able to set the default value in the schema to an empty list. If a transform modifies the value you may need to make sure it doesn't set a default as well. If that isn't doing the trick I'll take a look tomorrow morning

**Comment by nhalm2** [comment]
@bitwalker I was able to get this schema to work:
```
[
  mappings: [
    "complex_list.*": [
      to: "my_app.complex_list",
      datatype: [list: :complex],
      default: []
    ],
    "complex_list.$person.type": [
      to: "my_app.complex_list.$person.type",
      datatype: :atom,
      default:  :undefined
    ],
    "complex_list.$person.age": [
      to: "my_app.complex_list.$person.age",
      datatype: :integer,
      default: 30,
      validators: ['Conform.Validators.RangeValidator': 1..100]
    ],
  ],
  transforms: []
] 
```

This is the result:
```
[my_app: [complex_list: []]]
```

I did that on the 2.1.2 release tag, and that is what I am looking for.  Now my problem is I put the exact same config in an umbrella app, add conform to the top-level mix file, and then run `mix conform.effective --app=na_server` and I get this again:
```
[vagrant@localhost na]$ mix conform.effective --app=na_server
App not found!

App not found!

App not found!

[complex_list: ["$person": [age: 30, type: :undefined]]]
App not found!

[complex_list: ["$person": [age: 30, type: :undefined]]]
```

I have the 2.1.2 version in my deps.  I'll keep looking into it.  I really want this to work because we gave some ridiculously configs and this is `*.conf` is really a sysadmin's dream.  If you have any insight I would appreciate it very much.

**Comment by bitwalker** [comment]
Could you give master a shot? There are a number of changes which you'll want, including some fixes for umbrellas :)

**Comment by nhalm2** [comment]
I'll get something together for you.  Thanks a lot for the help.

**Comment by nhalm2** [comment]
I created an umbrella app.
https://github.com/nhalm2/conform_example

When I run `mix conform.effective --app=app1`:
```
[vagrant@localhost conform_example]$ mix conform.effective --app=app1
[clients: ["$client": [host: nil]]]
[clients: ["$client": [host: nil]]]
```
I expect:
```
[clients: []]
```

Here is an example of when I build the release and then try to run it:
```
[vagrant@localhost conform_example]$ MIX_ENV=prod mix release --env=prod --name=master
==> Assembling release..
==> Building release master:0.1.0 using environment prod
==> Including ERTS 8.1 from /usr/lib64/erlang/erts-8.1
==> Packaging release..
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/prod/rel/master/bin/master console
      Foreground: _build/prod/rel/master/bin/master foreground
      Daemon: _build/prod/rel/master/bin/master start
[vagrant@localhost conform_example]$ _build/prod/rel/master/bin/master console
Erlang/OTP 19 [erts-8.1] [source-77fb4f8] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

["$client": [host: nil]]

17:41:07.447 [info]  Application master exited: Master.start(:normal, []) returned a bad value: ["$client": [host: nil]]
{"Kernel pid terminated",application_controller,"{application_start_failure,master,{bad_return,{{'Elixir.Master',start,[normal,[]]},[{'$client',[{host,nil}]}]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,master,{bad_return,{{'Elixir.Master',start,[normal,[]]},[{'$client',[{host,nil}]}]}}})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by nhalm2** [comment]
Thank you!

**Comment by bitwalker** [comment]
@nhalm2 Could you update your dep to `{:conform, github: "bitwalker/conform", tag: "2.2.0"}` and let me know if everything looks good to you? There are a number of improvements there, including a fix for the issue you raised.

**Comment by nhalm2** [comment]
@bitwalker Ichanged the dep and got this:
```
[vagrant@localhost conform_example]$ mix deps.update --all
* Getting conform (https://github.com/bitwalker/conform.git)
remote: Counting objects: 1572, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 1572 (delta 6), reused 0 (delta 0), pack-reused 1538
Receiving objects: 100% (1572/1572), 34.76 MiB | 10.35 MiB/s, done.
Resolving deltas: 100% (854/854), done.
Running dependency resolution...
Dependency resolution completed:
  distillery 1.1.2
  neotoma 1.7.3
[vagrant@localhost conform_example]$ MIX_ENV=prod mix release --env=prod --name=master
Compiling src/conform_parse.peg
PEG manifest updated
==> conform
Compiling 1 file (.erl)
Compiling 19 files (.ex)
Generated conform app
==> Assembling release..
==> Building release master:0.1.0 using environment prod
==> Including ERTS 8.1 from /usr/lib64/erlang/erts-8.1
==> Failed to build release:
    {:overlay_failed, :enoent, "/home/vagrant/dev/conform_example/_build/prod/lib/conform/priv/bin/pre_configure.sh", {:copy, "/home/vagrant/dev/conform_example/_build/prod/lib/conform/priv/bin/pre_configure.sh", "releases/<%= release_version %>/hooks/pre_configure.d/00_conform_pre_configure.sh"}}
```

**Comment by bitwalker** [comment]
Ah, you'll need to use `master` of Distillery as well.

**Comment by nhalm2** [comment]
Added Distillery `master` and now this is looking spot on.  Thanks so much for your help!

**Comment by bitwalker** [comment]
Great! I'll be publishing new releases of both conform and distillery today :)
