### ISSUE TITLE
Fails to generate schema for pooler configuration

### ISSUE THREAD

**Issue by technomage** [bitwalker/conform#114]
The following is in our config.exs file for Risk pool configuration:

config :pooler, pools:
  [
    [
      name: :riaklocal1,
      group: :riak,
      max_count: 10,
      init_count: 9,
      start_mfa: { Riak.Connection, :start_link, ['127.0.0.1',8087] }
    ]
  ]

Conform generated the following schema:

    "pooler.pools": [
      commented: false,
      datatype: [
        list: [
          list: [
            atom: :atom,
            atom: :integer,
            atom: atom({:list, [:charlist, :integer]})
          ]
        ]
      ],
      default: [
        [name: :riaklocal1, group: :riak,
        max_count: 10, init_count: 9,
        start_mfa: Elixir.Riak.Connection('127.0.0.1', 8087)]
      ],
      doc: """
      Riak pooler config for use by the data generator
      """,
      hidden: false,
      to: "pooler.pools"

which does not compile.  It looks like a list of keywords is not supported out of the box?  I guess the intended approach would be to have a more "user friendly" config and use transforms to build the actual config.  I will proceed with that.  But, generating a bad config is probably worse than issue a warning or error for a type not supported.

**Comment by bitwalker** [comment]
There's a bug in translating the config to a default schema there, but conform can definitely handle keyword lists (and nested keyword lists). In general though, highly complex mappings like that are to be avoided, as you mentioned - and you are correct, in this case it should have failed to generate the schema, but it looks like it choked on some part of the `start_mfa` bit, but managed to avoid raising an error.

**Comment by bitwalker** [comment]
Could you give master a shot? I believe this is now fixed.
