### ISSUE TITLE
Binary is interpreted since 2.3.2

### ISSUE THREAD

**Issue by DieMaske** [bitwalker/conform#119]
Hello,

we do use the following structure in our .conf file:
`survey.test=[{"user":"someuser", "password":"somepassword", "roles":["role1","role2"]}]`

the corresponding schema-rule does look like this:

```
mappings: [
"survey.test": [
      commented: true,
      datatype: :binary,
      default: [],
      doc: "Just a test",
      hidden: false,
      to: "survey.test"
    ],
],
```

before upgrading from 2.3.0 to 2.3.2 the input was the same as the output and we could process the data of survey.test via the transforms-property in our schema:

```
transforms: ["survey.test":
    fn conf ->
      case Conform.Conf.get(conf, "survey.test") do
        [{_, json_string}] -> Poison.decode!(json_string)
        _ -> []
      end
    end],
```

This just worked fine, but since version 2.3.2 we do get an error with the following stacktrace:

```
** (Conform.Translate.TranslateError) Invalid value for survey.test: Expected value of type `:binary`, got [['{"user":"someuser"', 'password', ':"somepassword"', 'roles', ':["role1"', 'role2'], '}]']
    (conform) lib/conform/translate.ex:328: Conform.Translate.parse_datatype/3
    (conform) lib/conform/translate.ex:145: anonymous fn/6 in Conform.Translate.convert_types/2
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (conform) lib/conform/translate.ex:142: Conform.Translate.convert_types/2
    (conform) lib/conform/translate.ex:108: Conform.Translate.apply_schema/2
    (conform) lib/conform/translate.ex:84: Conform.Translate.to_config/3
    (conform) lib/conform.ex:102: Conform.process/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

We tried to figure out the changes, but couldn't find a starting point. Can you reproduce this error or do you have release notes of the new version?

Thanks in advance
DieMaske

**Comment by MichaelKunze** [comment]
Ran into the same problem. Any progress?

**Comment by bitwalker** [comment]
The issue here is that you are using syntax in the config file which is used by the config parser. You need to quote the JSON string, and escape the embedded quotes. The parser in 2.3.0 had a few bugs, which was likely why this worked at all to begin with, but it really shouldn't have.
