### ISSUE TITLE
Distillery custom command not running with conform configuration values

### ISSUE THREAD

**Issue by dpehrson** [bitwalker/conform#120]
Hello all, I have the following shell script registered in my distillery configuration as the `migrate` custom command:

```sh
#!/bin/sh

bin/myapp command Elixir.MyApp.Releases.Tasks migrate
```

The actual function is modeled very closely after the one in the distillery documentation.

However after building and deploying a release, attempting to run it results in an error:

```
$ bin/myapp migrate
Loading app: myapp...
> Starting dependency: ecto...
> Starting dependency: postgrex...
> Starting repo: Elixir.MyApp.Web.Repo...
> Running migration: Elixir.MyApp.Web.Repo...
15:22:34.960 [error] Postgrex.Protocol (#PID<0.103.0>) failed to connect:
** (DBConnection.ConnectionError) tcp connect (db:5432): non-existing domain - :nxdomain
```

In this case the `db:5432` would be the default database host/port from my mix configs, not the proper value included in the conform .conf packaged with the release.

If I start a remote console and execute the MFA manually, everything works fine:

```
$ ./bin/myapp remote_console
Erlang/OTP 19 [erts-8.2.2] [source-1ca84a4] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(myapp@127.0.0.1)1> Elixir.MyApp.Releases.Tasks.migrate
Loading app: myapp...
> Starting dependency: ecto...
> Starting dependency: postgrex...
> Starting repo: Elixir.MyApp.Web.Repo...
> Running migration: Elixir.MyApp.Web.Repo...
Unloading app: myapp...

15:24:34.773 [info]  Already up
Success, stopping...
:ok
```

My question is what the intended behavior here?

1. This should work, but I am doing something wrong
2. This should work, but it's a bug in conform and/or distillery
3. This is not supposed to work and I need to find another way to run migrations on deploy

Any insight into which one of these it is would be greatly appreciated, last checkbox on getting my deployments going 😀

**Comment by umatomba** [comment]
Hi @dpehrson. The issue is that the `command` don't run a conform hook (https://github.com/bitwalker/distillery/blob/master/priv/templates/boot.eex#L782). You can try to use SYS_CONFIG_PATH variable, to tell where right/old sys.config is placed and trigger conform manually, but i think we need some better solution. Ping @bitwalker

**Comment by umatomba** [comment]
I also see, pre_hooks was added but after some time removed again (https://github.com/bitwalker/distillery/commit/b8f45e16b83c3831fb24fce3957ed7a3382bfd38#diff-8e1a1749b553223a5202b250e93f3e57)

Maybe the using of configured hooks may be the solution for all problems here? In this case someone who needs it can enable some special hook using release configuraton like here: https://hexdocs.pm/distillery/boot-hooks.html#content

**Comment by dpehrson** [comment]
For what its worth. I've since removed conform from my deployment process and switched back to simply using distillery with `REPLACE_OS_VARS`. It's a much simpler setup I would recommend for anyone who doesn't REALLY need the "ops friendly config file".

**Comment by bitwalker** [comment]
The solution here is for me to expose functions to custom commands to run hooks for various phases, e.g. `run_hooks pre_start`, which would then allow custom commands to use hooks as needed.

@dpehrson I would absolutely agree, the use case is oriented more towards handing your apps off to an ops team or even customers (my current situation), in which case conform is a complex, but extremely useful solution.

**Comment by dpehrson** [comment]
@bitwalker Distillery and conform are both awesome, I think most of my confusion stemmed from the fact that conform wasn't a tool I needed to use for my particular situation (lone dev/op)

Thanks for all your hard work on both pieces of software.

**Comment by bitwalker** [comment]
Yeah definitely understandable - I wish it was easier to use, but I've never had the spare time to work on that aspect of the project :(. Thanks for the kind words!
