### ISSUE TITLE
no function clause matching in Conform.Translate.to_config/3

### ISSUE THREAD

**Issue by ngw** [bitwalker/conform#128]
Hi, it's a few days I'm losing my mind on a problem with conform (2.3.7) that can't read my configuration and use it to start a distillery app (1.4.1).
My question is mostly about how to debug this, because the problem is gathering enough informations to understand the problem.
First of all the error raised: https://gist.github.com/ngw/d37fbb9fd126dac1ac64a32dc1cf131b
MIX_ENV=prod mix conform.configure generates a configuration that seems perfectly fine, and perfectly fine is the output from  MIX_ENV=prod mix conform.effective
The only thing that confuses me is that after writing a transform to deal with guardian ttl (the infamous {30, :days}) it shows transform: []
 
How can I have a more meaningful error message to understand what's going on?

**Comment by bitwalker** [comment]
Looking into this shortly!

**Comment by bitwalker** [comment]
Could you give 2.3.8 a shot? It looks like the escript was outdated - either that or you weren't actually on 2.3.7 (this can happen if you forget to run `mix deps.update` after updating `mix.exs`).

**Comment by bitwalker** [comment]
2.3.9 is now out with some other improvements and small fixes - let me know how it goes!

**Comment by ngw** [comment]
Hi, I'm under 2.4.0 now, and absolutely nothing changed. I really don't know what else to do.
I'll try to post my schema and config here:

https://gist.github.com/ngw/c41a55f221177d1f7a059e38778aa62e
https://gist.github.com/ngw/64f31f0ac76bc66abdb65358d0a00a72

I'd like to note that when I deploy the transform array is still empty, and as you can see there's a transformation in my schema (the ttl).
What should I do now? My deploy fails

**Comment by ngw** [comment]
BTW
     
    ngw@blackstar  ~/hedging-ledger   master  cat mix.lock|grep conform
    "conform": {:hex, :conform, "2.4.0", "09ced3c81630885ecd6fb1ca696f3ca58ba4d705e51dc4bab2620c304ea0f9c9", [:mix], [{:neotoma, "~> 1.7.3", [hex: :neotoma, repo: "hexpm", optional: false]}], "hexpm"},

**Comment by bitwalker** [comment]
To be clear - you are still seeing the error message from the original post?

**Comment by ngw** [comment]
Yes, it's the same error message.

**Comment by bitwalker** [comment]
I'll try and reproduce later tonight or in the morning and get back to you, sorry for the trouble!

**Comment by ngw** [comment]
Alright, this was crazy hard but I found the culprit.
After building the release we're using fpm-cookery and that is what is building an old conform (2.1.1). That old conform doesn't obiously do well with the files created by 2.4.0.
Hopefully this will come handy to someone else before they come bothering you like we did. 
Thanks a lot for your help.

**Comment by bitwalker** [comment]
Oh wow, nice find! I was losing my mind because the stack traces didn't match the source code for the version and I had no idea how that was possible. Thanks for reporting back!
