### ISSUE TITLE
Add support for wildcard keys and complex datatypes

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/conform#13]
For some configuration, the current state of conform doesn't offer enough flexibility. If someone wants a list or map of values, for example:

```elixir
[[name: "buzz", type: :person, age: 25],
 [name: "fido", type: :dog, age: 5]]
```

Currently there is no way to define a mapping from a value in the .conf to that format. The proposal for supporting this scenario looks something like the following:

```
# my_app.conf
my_app.complex_list.buzz.type = person
my_app.complex_list.buzz.age = 25
my_app.complex_list.fido.type = dog
my_app.complex_list.fido.age = 5
```
```elixir
# my_app.schema.exs
[mappings: [
    "my_app.complex_list.*": [
    to: "my_app.complex_list",
    datatype: [complex: {"my_app.complex_list.*.type", "my_app.complex_list.*.age"}],
    default: []
  ]
  "my_app.complex_list.*.type" [
    to: "my_app.complex_list",
    datatype: :atom,
    default: :undefined
  ],
  "my_app.complex_list.*.age" [
    to: "my_app.complex_list",
    datatype: :integer,
    default: 0
  ]]
translations: [
  "my_app.complex_list.*": fn
    _, {name, {type, age}}, nil -> [[name: name, type: type, age: age]]
    _, {name, {type, age}}, acc -> [[name: name, type: type, age: age] | acc]
  ]]
```

Stated more plainly, the tasks to implement this are as follows:

- [ ] Automatically initialize accumulators to `[]`
- [ ] Add wildcard support to keys.
- [ ] Add a `complex` data type, which takes a tuple of keys to mappings which will populate that position in the tuple passed to the translation (or simply returned if no translation is provided)
- [ ] When a complex datatype is encountered, get the mappings for that datatype, and extract the values from the .conf parse result, and create a tuple with those mapped values.
- [ ] Skip further processing of the mappings used by the complex type

I'm open to suggestions, improvements, etc. Please provide examples of all three files (.conf, .schema.exs, and sys.config) so that it's clear what the inputs and outputs are.

**Comment by liveforeverx** [comment]
For your information, we have started to work on [this](https://github.com/0xAX/conform/tree/conform-wildcard) feature.

**Comment by bitwalker** [comment]
@liveforeverx Awesome! Let me know when you feel it's ready to merge and I'll be glad to do so!

**Comment by bitwalker** [comment]
Support for this has been merged! Just need some documentation around it and we can call this good for now I think

**Comment by liveforeverx** [comment]
@bitwalker Can be closed now?

**Comment by bitwalker** [comment]
Oh yep, still working on cleaning up the issue tracker. Thanks! :)
