### ISSUE TITLE
Failing to parse binary

### ISSUE THREAD

**Issue by evax** [bitwalker/conform#136]
Conform is failing to parse my config file with this error:

```Expected value of type `:binary`, got "$date $time [$metadata] [$level] [$message]\n"```

That looks like a legit `:binary` to me.

Looking at the code it seems it's always expecting things to be wrapped in a list:
https://github.com/bitwalker/conform/blob/master/lib/conform/translate.ex#L321-L326

Applying the following patch fixes the issue locally:
```diff --git a/lib/conform/translate.ex b/lib/conform/translate.ex
index 84fe4c7..94dd83b 100644
--- a/lib/conform/translate.ex
+++ b/lib/conform/translate.ex
@@ -140,7 +140,7 @@ defmodule Conform.Translate do
         for {conf_key, value} <- results, not datatype in [:complex, [list: :complex]] do
           parsed = case value do
             nil -> default
-            _   -> parse_datatype(datatype, value, mapping)
+            _   -> parse_datatype(datatype, List.wrap(value), mapping)
           end
           :ets.insert(table, {conf_key, parsed})
         end
```

**Comment by bitwalker** [comment]
Damn, can't believe that was missed. Nice catch! I can make the patch myself, but if you'd like the credit, open up a PR with your patch and I'll merge it right away. Thanks!

**Comment by evax** [comment]
Glad I could help, thanks for the amazing tooling work you've been doing!
https://github.com/bitwalker/conform/pull/137

**Comment by bitwalker** [comment]
I'll publish a new release this afternoon with your fix, thanks again!
