### ISSUE TITLE
UndefinedFunctionError - module Conform.Conf is not available

### ISSUE THREAD

**Issue by highbass** [bitwalker/conform#140]
I am following the guidelines to get conform running and run into the following error and can't seem to figure out whats causing it.

```
$ mix conform.new
                                                                                                                                  
==> arena_web
You already have a schema at config/arena_web.schema.exs.
Do you want to overwrite this schema with a new one?
 [Yn] y

==> The schema for your project has been placed in config/arena_web.schema.exs

==> arena_engine
You already have a schema at config/arena_engine.schema.exs.
Do you want to overwrite this schema with a new one?
 [Yn] y
```

```
$  mix conform.configure                                                                                                                                                          
==> arena_web
You already have a .conf at config/arena_web.dev.conf.
Do you want to overwrite this config file with a new one?
 [Yn] y

==> The .conf file for arena_web has been placed in config/arena_web.dev.conf

==> arena_engine
You already have a .conf at config/arena_engine.dev.conf.
Do you want to overwrite this config file with a new one?
 [Yn] y

==> The .conf file for arena_engine has been placed in config/arena_engine.dev.conf
```

This is the part that throws the error. I can't seem to figure out whats causing it.

```
$ mix conform.effective                                                                                                                                                           
==> in arena_web
** (UndefinedFunctionError) function Conform.Conf.from_file/1 is undefined (module Conform.Conf is not available)
    Conform.Conf.from_file("/Users/zbutt/work/wgames/arena/apps/arena_web/config/arena_web.dev.conf")
    lib/mix/tasks/conform.effective.ex:95: Mix.Tasks.Conform.Effective.do_run/1
    (mix) lib/mix/project.ex:332: Mix.Project.in_project/4
    (elixir) lib/file.ex:1277: File.cd!/2
    lib/mix/tasks/conform.effective.ex:62: anonymous fn/3 in Mix.Tasks.Conform.Effective.run/1
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/conform.effective.ex:60: Mix.Tasks.Conform.Effective.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
```

**Comment by bitwalker** [comment]
That's very strange - did you upgrade conform recently? What version is this by the way?

**Comment by highbass** [comment]
@bitwalker it is version 2.5.2

**Comment by bitwalker** [comment]
@highbass What happens if you add conform as a dep to each of the child applications in the umbrella? I think I know what's going on here, but want to confirm it is what I think it is.

**Comment by highbass** [comment]
ooo that did the trick! works fine after your suggestion.

**Comment by highbass** [comment]
@bitwalker I am not sure if this is related to the current release or I am just making a dumb mistake. The real issue that I am having is trying to get distillery and conform working together. I generated my schema/conf files and then went ahead and created my release

`$ mix release
...
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/dev/rel/arena/bin/arena console
      Foreground: _build/dev/rel/arena/bin/arena foreground
      Daemon: _build/dev/rel/arena/bin/arena start
`

and under my _build/dev/rel/arena/releases/0.1.0 i can see the appropriate arena.conf and schema files generated. However, when I try to run my app I get the following error

`$ _build/dev/rel/arena/bin/arena foreground                                                                                                                      
Failed to start Elixir.
error: {error,{elixir,{"no such file or directory","elixir.app"}}}
`

The minute i remove conform 'plugin Conform.ReleasePlugin' from my distillery confix.exs (under rel/) and rebuild the package, the problem disappears.

**Comment by highbass** [comment]
I figured it out after some intense debugging. Setting "set include_erts: true" fixed the problem ... seems like an escript issue potentially related to https://github.com/elixir-lang/elixir/issues/2970

**Comment by bitwalker** [comment]
Conform doesn't embed Elixir, but rather sets ERL_LIBS to point to the elixir libs included in the release. I suspect there may be an issue if the Erlang running the release does not match the one it was built with, but that was one of the original motivating reasons for *not* embedding Elixir (i.e. the same version of Conform could work on both OTP 19 and 20, while embedding Elixir would fail on one or the other depending on what version of Erlang compiled the escript).

I'll try and reproduce though, unfortunately it's a tricky situation :( - I've tried building the escript on demand (a long time ago now), but that had the same problem if building on one system and deploying to another, so ultimately that was more pain than it was worth.
