### ISSUE TITLE
Environment variables should override .conf values

### ISSUE THREAD

**Issue by aeons** [bitwalker/conform#145]
I would prefer environment variables to override values that are set in .conf files.

This means that you can deploy the app with a set of sane defaults, and then easily change the configuration at runtime by setting environment variables.

We deploy stuff using containers, so editing files to eg. increase the log verbosity is not ideal.

Of course you could just use environment variables for everything, but that also gets extremely verbose.

What do you think?

**Comment by lachezar** [comment]
You could set defaults in the schema file, which will be overridden by env vars if defined.

**Comment by aeons** [comment]
Yeah, that is one solution, it still isn't optimal IMO.
