### ISSUE TITLE
Support for tuples

### ISSUE THREAD

**Issue by vasspilka** [bitwalker/conform#146]
I see there is no support for the tuple type, [guardian](https://github.com/ueberauth/guardian) and [quantum](https://github.com/c-rack/quantum-elixir) use tuples for their configuration also we use it for some of our specific configuration.

I can see the problems with the tuple type, just opening a discussion.

**Comment by mertonium** [comment]
This is also a problem for the [redix_sentinel](https://hex.pm/packages/redix_sentinel) lib - where the mix config looks like:
```elixir
config :my_app, :sentinel_config,
    sentinels: [
      [host: "10.200.X.X", port: 26379],
      [host: "10.200.X.X", port: 26379],
      [host: "10.200.X.X", port: 26379]
    ],
    role: "master",
    group: "misc"
```
@bitwalker if you could provide some guidance on how a config like this is supposed to look in `.conf` format, I could take a crack at implementing a `write_datatype` function.

**Comment by mertonium** [comment]
@vasspilka - for what it's worth, I solved my problem with transforms.

I changed my schema to look like this:
```elixir
...
"my_app.blocklist_redis.sentinels": [
  commented: false,
  datatype: [list: :ip],
  doc: "Sentinel host:port combinations",
  hidden: false,
  to: "my_app.blocklist_redis.sentinels"
],
"my_app.blocklist_redis.role": [
  commented: false,
  datatype: :binary,
  doc: "Sentinel role",
  hidden: false,
  to: "my_app.blocklist_redis.role"
],
"my_app.blocklist_redis.group": [
  commented: false,
  datatype: :binary,
  doc: "Sentinel group",
  hidden: false,
  to: "my_app.blocklist_redis.group"
],
...
```
and then added a transform like this:
```elixir
transforms: [
  "my_app.sentinel_config": fn pid ->
    # Helper function to convert a list of :ip types into a list of [host: x.x.x.x, port: xxxx] tuples
    # (I haven't quite figured out how to use "import" yet :) )
    ip_reducer = fn val ->
      Enum.reduce(val, [], fn {host, port}, acc ->
        [[host: host, port: String.to_integer(port)] | acc]
      end)
    end

    redis_config =
      pid
      |> Conform.Conf.find("my_app.sentinel_config.$")
      |> Enum.reduce(Keyword.new, fn {[_, _, _, key], val}, acc ->
        cond do
          is_nil(val) -> acc
          is_list(val) -> Keyword.put_new(acc, List.to_atom(key), ip_reducer.(val))
          true -> Keyword.put_new(acc, List.to_atom(key), val)
        end
      end)

    Conform.Conf.remove(pid, "my_app.sentinel_config.$")
    redis_config
  end
],
```

**Comment by vasspilka** [comment]
Yes, that's what I ended up doing as well :) . I am closing this issue in favor of Transforms https://hexdocs.pm/conform/getting-started.html#content Sadly they are not well documented but that is another issue, I could great a PR with better docs for Transforms, Types @bitwalker is there interest for this?
