### ISSUE TITLE
Allow more flexibility in keys

### ISSUE THREAD

**Issue by johnfoconnor** [bitwalker/conform#16]
# conform does not support keys which contain `.`

desired sys.config

```
[
{my_app, [{'Elixir.Bar', value}]}
]
```

Conform splits the `to` keypath on `.` which makes the above sys.config impossible. 
# keys can only be `atom`s

desired sys.config

```
[{other_app, [{<<"some.string">>, value}]}]
```

Conform expects each key component to be converted to an atom

**Comment by yrashk** [comment]
Any updates on this? I am also running into this issue.

**Comment by bitwalker** [comment]
@yrashk Are you running into the string key issue specifically? If so, I'll probably work on adding support for quoted keys to the conf grammar.

@stocks29 What do you think about the above? So to use string-based keys, you'd do `someapp."some arbitrary key" = foo`?

**Comment by yrashk** [comment]
I was running into the Camel.Case keys issue

**Comment by stocks29** [comment]
@bitwalker I think that seems reasonable and straight-forward.

**Comment by bitwalker** [comment]
@stocks29 Could you test with master and let me know what issues, if any, you run in to? Quoted keys are now supported in the parser.

**Comment by smpallen99** [comment]
Here is part of my config that is causing issues: 

```elixir
 login_defaults: [
    {"/orange", "initiate@example.com"},
    {"/orange/monitor", "admin@example.com"},
  ],
  phone_number_order: [
    {"Primary Phone", "1"},
    {"Secondary Phone", "2"},
  ]
```
I would even be happy if I could do the following in my schema:
```
myapp.settings.phone_number_order: [
```
  default: [
    {"Primary Phone", "1"},
    {"Secondary Phone", "2"}
  ]
```

**Comment by martin-langhoff** [comment]
Dupe with #47 , or just major overlap ?

**Comment by bitwalker** [comment]
Lists with arbitrary subtypes are now working properly in master, please open a new issue if there are any problems.
