### ISSUE TITLE
RFC: Breaking changes for the greater good

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/conform#44]
Hi all (I hope people are listening!),

I've been working on some significant improvements to how conform works today. One of the biggest problems I've been working on is a more intuitive way to do mappings/translations for complex types. For instance, let's say you want to get the following config output:

```elixir
[ lager: [ handlers: [
  lager_console_backend: [ level: :info ],
  lager_file_backend: [ level: :error, path: "/var/log/error.log" ],
  lager_file_backend: [ level: :info, path: "/var/log/info.log" ] ]
```

So you write a schema that looks like this:

```elixir
[ mappings: [
   "lager.handlers.*": [
     to: "lager.handlers",
     datatype: [list: :complex],
     default: [],
     ... ],
   "lager.handlers.console.level": [
     to: "lager.handlers.lager_console_backend.level",
     datatype: [enum: [:info, :error]],
     default: :info,
     ...],
   "lager.handlers.file.*": [
      to: "lager.handlers.lager_file_backend",
      datatype: [list: :complex],
      default: [],
      ...],
   "lager.handlers.file.error": [
      to: "lager.handlers.lager_file_backend.error",
      datatype: :binary,
      default: "/var/log/error.log",
      ...],
    "lager.handlers.file.info": [
      to: "lager.handlers.lager_file_backend.info",
      datatype: :binary,
      default: "/var/log/info.log",
      ...] ],
  translations: [
    "lager.handlers.lager_file_backend.error": fn _mapping, {_, path} ->
      [level: :error, path: path]
    end,
    "lager.handlers.lager_file_backend.info": fn _mapping, {_, path} ->
      [level: :info, path: path]
    end
  ] ]
```

For one, the above does not work. In fact I've found that there isn't actually a way to do this properly that works to cover a variety of edge cases. It is also unintuitive, contains a lot of what is effectively boilerplate/garbage mappings, and already contains bits which are difficult to understand in context (for instance, what args are passed to the translations, what are their values?).

I'm working on, and would like feedback on my solution to these problems. I'm planning on conforming more closely to the way cuttlefish handles this, so our schema would look more like the following:

```elixir
[ mappings: [
   "lager.handlers.$backend.level": [
     to: "lager.handlers.lager_$backend_backend.level",
     datatype: [enum: [:info, :error]],
     default: :info, ... ],
   "lager.handlers.file.error": [
      to: "lager.handlers.lager_file_backend.error",
      datatype: :binary,
      default: "/var/log/error.log",
      ...],
    "lager.handlers.file.info": [
      to: "lager.handlers.lager_file_backend.info",
      datatype: :binary,
      default: "/var/log/info.log",
      ...] ],
  translations: [
    "lager.handlers": fn conf ->
        file_handlers = Conform.Conf.get(conf, "lager.handlers.lager_file_backend.$level")
        |> Enum.map(fn {[_, _, backend, level], path} -> {backend, [level: level, path: path]} end)
        console_handlers = Conform.Conf.get(conf, "lager.handlers.lager_console_backend")
        |> Enum.map(fn {[_, _, backend], conf} -> {backend, conf} 
        console_handlers ++ file_handlers
    end
  ] ]
```

In a nutshell:

- Wildcards in mappings are now bound to variable names, and those variables can be used in the `to` key path.
- After all mappings are performed, the translations are run, translation keys define the path at which the translated value will be placed. The result of applying the translation will overwrite the value at that path if one exists.
- A new module `Conform.Conf` will be exposed to schemas, which provides functions for querying the configuration state for data. In the above example, `get` is a function which allows you to fetch values based on a key path, which can contain variables. The result of `get` will always be a keyword list, where the key is the tokenized path (as atoms), and the value is the configuration at that path.
- The `conf` argument will also contain configuration read from `config.exs` that isn't exposed via the .conf.

I think the above significantly reduces the complexity of conform's implementation, while also providing more powerful tools for manipulating the configuration which is output.

As part of this sweep of changes, I'm also planning on introducing validators, which can be applied to mappings (prior to translations). And the following new mapping settings:

- `commented` - Boolean, if true will write the default value to the conf, but comment it out.
- `required` - Boolean, if true will throw an error if the value is not present in the conf
- `hidden` - Boolean, will not write the setting to the conf when generated, in this way you can define advanced settings which can be configured, but which won't be shown to users of the .conf by default

I'd like to get feedback on all of this, as they are significantly large breaking changes. I wish we could avoid such a large set of changes, but after a lot of work in private, I'm beginning to see how the current architecture is not very flexible moving forward, and is currently error prone for some cases. I really think this is worth the pain, but I want to make sure others feel that way as well.

For many of you, these changes may not actually affect you, but for those using translations, or wildcard mappings, it will.

**Comment by bitwalker** [comment]
Just a note, I'm also planning on adding the ability to import schemas from dependencies (see #43).

**Comment by bitwalker** [comment]
I've pushed the release candidate of this RFC to the `v1` branch. If you are watching, please take a look and give me feedback!

**Comment by tverlaan** [comment]
Hi,

I haven't used translations yet but I expect to somewhere in the future. To that end I can't really comment on making breaking changes or not. However I do see the benefits of using the second syntax, so :+1: for me.
One thing that I have doubts on is the syntax of the variables. In your example it is not possible to use `$some_variable`. Have you run into more complex configuration schemes where longer variable names make sense? I can imagine there are situations where you would want that but I'd have yet to come up with one.

That's it for now. Thanks for Conform!

**Comment by Greatlemer** [comment]
Hi,

After having just tried to get my head around the existing method of specifying complex structures in the schema then discovering this RFC, I have to say the new version is far simpler to implement and I look forward to it being released fully.
In the meantime I would like to try and make use of it with my existing project but when I try to build it with exrm 0.19.9 I get an `undefined function: Conform.Schema.read!/1` error (which is understandable as that doesn't exist any more). I tried using the v1 branch of exrm however and in that case it didn't include anything to do with my configuration in the release. Is there any special configuration that's required to use it?

**Comment by bitwalker** [comment]
@Greatlemer Sorry about the delay, I would use the `v1` branch of exrm with conform 1.0.0-rc*. I'll be promoting v1 of exrm very soon, just trimming down the open issues a bit before I do. v1 of exrm is basically 0.19.x with some changes to be compatible with the deprecation of the direct dependency on conform.

**Comment by Greatlemer** [comment]
@bitwalker, no worries, I had tried that combination before without success. It turns out (as I discovered yesterday) that it was down to some sort of version conflicts as when I'd upgraded to the new github versions the older versions were still lingering in my deps folder. Once I removed them the release contained everything it should.
Good luck with getting to the v1 releases of both. I look forward to seeing them, although the latest versions are good enough to keep me going for now :)

**Comment by bitwalker** [comment]
@Greatlemer I suspect it was because your `mix.lock` had the old revisions :). It's caught me a few times too, but the easy way to fix it is just `mix do deps.unlock <app>, deps.update <app>`. Hopefully I'll have 1.0 out in the next week or so!

**Comment by Greatlemer** [comment]
I think it was the `deps.update` step that I messed up on. I definitely unlocked them but then I did a `deps.get` again. Somehow I ended up with two versions in my deps directory.
Thank you very much for the assistance though.
