### ISSUE TITLE
Why the restriction on environment names?

### ISSUE THREAD

**Issue by Soulforged** [bitwalker/conform#48]
Hi,

Currently some tasks, like **conform.effective** validates the environment used to execute it. Is this really necessary? For instance I use more than just three valid environments, and the task requires it to pass this test:

```elixir
unless env in [:test, :dev, :prod] do
   error "The value provided for --env is not a valid environment"
   exit(:normal)
end
```

I've already modified the code locally to do what I want, and I've noticed no issues, if this isn't necessary I could create a pull request.

**Comment by bitwalker** [comment]
@Soulforged I'll gladly accept a PR with your changes :)
