### ISSUE TITLE
Elixir.ReleaseManager.Plugin.Conform before_release hook exrm is not locked 

### ISSUE THREAD

**Issue by dewie** [bitwalker/conform#53]
Having problem with version 

 {:exrm, "~> 1.0.0-rc5"},
 {:conform, "~> 1.0.0-rc4"}

 MIX_ENV=prod mix release
Building release with MIX_ENV=prod.
==> conform
Unchecked dependencies for environment prod:
* exrm (Hex package)
  the dependency is not locked (run "mix deps.get" to generate "mix.lock" file)
==> Failed to execute before_release hook for Elixir.ReleaseManager.Plugin.Conform!
==> qrgateway
** (Mix) Can't continue due to errors on dependencies

It works ok without conform

**Comment by bitwalker** [comment]
@dewie Could you run the following:

- `mix deps.get`
- `MIX_ENV=prod mix compile`
- `MIX_ENV=prod mix release`

And let me know if it still fails? I'm confused on how you could have gotten that message about the dependency not being locked, but the steps above should ensure that everything is fetched/locked and compiled before attempting to build the release.

**Comment by dewie** [comment]
Hi,

I have made a release today with exrm 19.9 today.
Added conform with your code and tried a release.
This worked

But when i added the following

mix conform.new
mix conform.configure
MIX_ENV=prod mix release

I got the same error


==> conform
Unchecked dependencies for environment prod:
* exrm (Hex package)
   the dependency is not locked (run "mix deps.get" to generate 
"mix.lock" file)
==> Failed to execute before_release hook for 
Elixir.ReleaseManager.Plugin.Conform!
==> qrgateway
** (Mix) Can't continue due to errors on dependencies


I also tried to generate the config with:

MIX_ENV=prod mix conform.new
MIX_ENV=prod mix conform.configure


I have attached the generated conform files







Met vriendelijke groet,

itXL
Daniel Wijnands

Tel: 0478-712016
Email: daniel@itxl.nl
Website: www.itxl.nl

On 27-11-15 18:16, Paul Schoenfelder wrote:
> @dewie <https://github.com/dewie> Could you run the following:
>
>   * |mix deps.get|
>   * |MIX_ENV=prod mix compile|
>   * |MIX_ENV=prod mix release|
>
> And let me know if it still fails? I'm confused on how you could have
> gotten that message about the dependency not being locked, but the steps
> above should ensure that everything is fetched/locked and compiled
> before attempting to build the release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitwalker/conform/issues/53#issuecomment-160178160>.
>

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.url.host here.
qrgateway.Elixir.Qrgateway.Endpoint.url.host = "example.com"

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.url.port here.
qrgateway.Elixir.Qrgateway.Endpoint.url.port = 80

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.root here.
qrgateway.Elixir.Qrgateway.Endpoint.root = "/home/daniel/development/elixir/qrgateway"

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.secret_key_base here.
qrgateway.Elixir.Qrgateway.Endpoint.secret_key_base = "DmgKGQ6s06cJ0lkRDlCqsCHZuuQ4m3SDi4+O3XMZNfcutSGGynPH5hFP+YaFd13/"

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.render_errors.accepts here.
qrgateway.Elixir.Qrgateway.Endpoint.render_errors.accepts = "html", "json"

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.pubsub.name here.
qrgateway.Elixir.Qrgateway.Endpoint.pubsub.name = Elixir.Qrgateway.PubSub

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.pubsub.adapter here.
qrgateway.Elixir.Qrgateway.Endpoint.pubsub.adapter = Elixir.Phoenix.PubSub.PG2

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.http.port here.
qrgateway.Elixir.Qrgateway.Endpoint.http.port = system = "PORT"

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.cache_static_manifest here.
qrgateway.Elixir.Qrgateway.Endpoint.cache_static_manifest = "priv/static/manifest.json"

# Provide documentation for qrgateway.Elixir.Qrgateway.Endpoint.server here.
qrgateway.Elixir.Qrgateway.Endpoint.server = true

# Provide documentation for qrgateway.Elixir.Qrgateway.Repo.adapter here.
qrgateway.Elixir.Qrgateway.Repo.adapter = Elixir.Mongo.Ecto

# Provide documentation for qrgateway.Elixir.Qrgateway.Repo.database here.
qrgateway.Elixir.Qrgateway.Repo.database = "qrg"

# Provide documentation for qrgateway.Elixir.Qrgateway.Repo.hostname here.
qrgateway.Elixir.Qrgateway.Repo.hostname = "localhost"

# Provide documentation for qrgateway.Elixir.Qrgateway.Repo.username here.
# qrgateway.Elixir.Qrgateway.Repo.username = 

# Provide documentation for qrgateway.Elixir.Qrgateway.Repo.password here.
# qrgateway.Elixir.Qrgateway.Repo.password = 

# Provide documentation for logger.console.format here.
logger.console.format = "$time $metadata[$level] $message
"

# Provide documentation for logger.console.metadata here.
logger.console.metadata = request_id

# Provide documentation for logger.level here.
logger.level = info

# Provide documentation for phoenix.generators.migration here.
phoenix.generators.migration = true

# Provide documentation for phoenix.generators.binary_id here.
phoenix.generators.binary_id = false

# Provide documentation for phoenix.template_engines.haml here.
phoenix.template_engines.haml = Elixir.PhoenixHaml.Engine

**Comment by bitwalker** [comment]
You can't use `conform` >= 1.x with `exrm` < 1.x, because the conform plugin for exrm was moved from exrm to conform, so if you use the new version of conform with the old version of exrm, there will be conflicts. The new version of the conform plugin is also depending on changes made in exrm 1.x. Could you try with exrm 1.0.0-rc6?

**Comment by dewie** [comment]
I was using exrm 1.0.0-rc5 , 1.0.0.6 gives me the same problem.

I can send you the project if that helps (just a small test application)





Met vriendelijke groet,

itXL
Daniel Wijnands

Tel: 0478-712016
Email: daniel@itxl.nl
Website: www.itxl.nl

**Comment by bitwalker** [comment]
Sure if you can send me a link to the test app, I'll clone it and test locally.

**Comment by dewie** [comment]
It is in a private repository,
I will send it by wetransfer (including _build folder) = 13mb.

Can i use paulschoenfelder@gmail.com ?





Met vriendelijke groet,

itXL
Daniel Wijnands

Tel: 0478-712016
Email: daniel@itxl.nl
Website: www.itxl.nl

**Comment by bitwalker** [comment]
Yep! No problem

**Comment by bitwalker** [comment]
@dewie Ok I found the issue with this, and pushed a fix and a new release 1.0.0-rc5. The problem was that the `conform.release` task changes the Mix env to prod when it builds the conform escript, however the exrm dependency won't be available when it does so (unless you `MIX_ENV=prod mix compile` first). Since that change of environment is not actually necessary, I've removed it for now.

**Comment by dewie** [comment]
Thanks!

Met vriendelijke groet,

itXL
Daniel Wijnands

Tel: 0478-712016
Email: daniel@itxl.nl
Website: www.itxl.nl
