### ISSUE TITLE
Does conform support custom data types?

### ISSUE THREAD

**Issue by alco** [bitwalker/conform#54]
The Readme says

> I currently am planning on supporting user-defined types, but that work has not yet been completed.

but then it also shows an example of creating a custom type.

I tried using one, but it doesn't seem to be invoked at all, parsing the corresponding value as a binary instead.

**Comment by bitwalker** [comment]
@alco Yes this has been implemented, I need to review and update the README, sorry about that. Could you share your custom type implementation and an example schema and conf showing it's use? I can help you figure out why it's not working, and then get that into the docs as an example for future reference.

**Comment by alco** [comment]
Take a look at this test repo https://github.com/alco/conformist

When I run `mix conform.effective`, I don't see the functions in the custom type being invoked at all, and no errors are printed. It just uses the value from `config.exs`.

**Comment by bitwalker** [comment]
@alco Looks like the problem here was that the loadpaths weren't set properly when the mix task runs (i.e. it can't find any modules from the calling project). I pushed a fix and a new release of conform, and also updated your example project so it works.

**Comment by alco** [comment]
Neat! Thanks!
