### ISSUE TITLE
Does the readme need updating?

### ISSUE THREAD

**Issue by brentonannan** [bitwalker/conform#57]
On the readme, the schema is listed as having mappings, and translations (as in cuttlefish), but in the generated schema, there's mappings, transforms, and validators. This leads me to think that the readme is quite a bit out of date - is this correct, or am I reading it wrong? Is there a canonical place for up to date documentation?

**Comment by bitwalker** [comment]
@brentonannan You are absolutely correct, I'll push updated documentation today sometime.

**Comment by bitwalker** [comment]
Updated the README and some other errors I spotted.

**Comment by brentonannan** [comment]
Thanks a lot mate =D

**Comment by rafal-radziszewski** [comment]
@bitwalker Currently there is example of translation using
```elixir
case _mapping, val ->
#code
end
```

Such expressions causes compilation error on Elixir 1.2 (case/3 not defined).

**Comment by bitwalker** [comment]
@rafal-radziszewski Fixed, thanks!
