### ISSUE TITLE
conform.release fails after the first run

### ISSUE THREAD

**Issue by alco** [bitwalker/conform#64]
If you clone this project https://github.com/alco/exrmtest and run `mix conform.release` in it, it'll work the first time. But every subsequent attempt produces the following output:

```
$ mix conform.release
==> conform
Unchecked dependencies for environment dev:
* neotoma (Hex package)
  the dependency is not locked (run "mix deps.get" to generate "mix.lock" file)
* ex_doc (Hex package)
  the dependency is not available, run "mix deps.get"
* earmark (Hex package)
  the dependency is not available, run "mix deps.get"
==> exrmtest
** (Mix) Can't continue due to errors on dependencies
```

When running it with `MIX_ENV=prod`, it only complains about `neotoma`:

```
$ MIX_ENV=prod mix conform.release
==> conform
Unchecked dependencies for environment prod:
* neotoma (Hex package)
  the dependency is not locked (run "mix deps.get" to generate "mix.lock" file)
==> exrmtest
** (Mix) Can't continue due to errors on dependencies
```

The errors appear to come from the invocation of `escript.build` but I haven't been able to investigate it further.

Elixir v1.2.3.

**Comment by bitwalker** [comment]
The release I pushed today removes that task entirely, as it's internal to exrm, and was causing problems for a variety of reasons.
