### ISSUE TITLE
Merging configs with nested lists

### ISSUE THREAD

**Issue by hogjosh** [bitwalker/conform#69]
I'm hesitant to consider this a bug outright, but I'll describe an example scenario.

If I create a release with 5 sublists defined for a particular key in prod.exs and need to deploy that release to a different environment where only 3 sublists are necessary (via a different .conf file), the merging process gives me the 3 sublists that I want, but also the last 2 from the initial prod.exs.  I can see how a strict merge and a replacement of the list both make sense in various scenarios.

I seem to be fighting an uphill battle with sublists, so maybe I'm approaching the problem incorrectly, but figured I'd open it to discussion.

**Comment by bitwalker** [comment]
It may help to see a simplified example with all of the configs involved, but it sounds like it may be desirable to have a setting which toggles the merging behaviour for a specific configuration key correct?

**Comment by bitwalker** [comment]
ping :)

**Comment by bitwalker** [comment]
Just FYI, in master, I've removed merging of nested lists, only keyword lists are merged, or unnested lists
