### ISSUE TITLE
Use schemes from projects which are not direct dependency

### ISSUE THREAD

**Issue by 0xAX** [bitwalker/conform#82]
Hello @bitwalker, I have some issues:

I need to merge schemes from dependency of my application and some of its dependencies in release. I see that I can use `extends` attribute for this purpose, but in the same way I see that conform uses `Mix.Dep.children/0` to collect dependency schemes.

This leads to following problem: What if I want to merge schema from not direct dependency, but for example schema from dependency of a dependency? In this way we will get:

```
** (CaseClauseError) no case clause matching: []
    lib/mix/tasks/conform.archive.ex:34: anonymous fn/4 in Mix.Tasks.Conform.Archive.run/1
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/conform.archive.ex:23: Mix.Tasks.Conform.Archive.run/1
    lib/conform_exrm.ex:27: ReleaseManager.Plugin.Conform.before_release/1
    lib/mix/tasks/release.ex:248: anonymous fn/2 in Mix.Tasks.Release.execute_before_hooks/1
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/release.ex:77: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Can I do it with the current conform? If not, what do you think If we will replace ` Mix.Dep.children` from the `conform.archive.ex` with `project_path/deps/extended_dep/config/schema`? 

I will send PR soon for following discuss.

And also I have second question. I see that some transformers are arirty 1 and some transformers are arity 3 in conform's README.md. For all of my transformers I'm getting:

    ** (Conform.Schema.SchemaError) Invalid transform for my_mapping, it must be a function of arity 1.

error. How can I use transformers with arity 3? 

Thank you.

**Comment by rixmann** [comment]
+1

**Comment by 0xAX** [comment]
Can be closed as fix already pushed https://github.com/bitwalker/conform/commit/a0ab7e51323f298977649246f38247231c960a38
