### ISSUE TITLE
Allow defining translation functions in a module for reuse.

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/conform#9]
It would be nice to be able to define a module of functions that can be reused for translations. Either as an importable script, or defined inline. It seems conform.effective handles this already, so potentially the only thing that needs to happen is to fix exrm's conform plugin, and work on some kind of support for importing a script containing the functions to use.

**Comment by 0xAX** [comment]
Hello @bitwalker, I'm working on this issue now and have no ideas how to find used modules to import it. What do you think if we'll add additional `import` field with the modules and path to the projects which contains this modules. Something like this:

```elixir
[
  mappings: [
  ...
  ...
  ...
  ],

  translations: [
  ...
  ...
  ...
  ],

  import: [
    Mod1: "/path",
    Mod2: "/path2"
  ]
```

What do you think about it? If you have any another suggestion, would be great to hear.
