### ISSUE TITLE
Schemas are reduced incorrectly during archival

### ISSUE THREAD

**Issue by martin-langhoff** [bitwalker/conform#90]
On top of #89 I am debugging in issue around https://github.com/bitwalker/conform/blob/master/lib/mix/tasks/conform.archive.ex#L33 . I can only describe it as "the accumulator drops items". My example schema "extends" two other schemas. Those are found, but the accumulator somehow drops them.

Pulling my hair out on this one.

**Comment by martin-langhoff** [comment]
Sorted out, appears in the latest patch on #89 ~

**Comment by bitwalker** [comment]
Merged #89, so I'll close this out
