### ISSUE TITLE
Conform with umbrella app, distillery and edeliver

### ISSUE THREAD

**Issue by akurkin** [bitwalker/conform#91]
hey guys,
I have an umbrella app with 5 apps within umbrella. I use distillery to build the release, and edeliver for deployment.
Distillery is configured to build single release for whole umbrella application which as well results in generating a single `sys.config` file.

Configuration is rather complex and I was hoping to use `conform`, but I'm struggling a bit with making it work. For example, when I run `mix conform.new` it goes into each app and generates a schema for each app under umbrella. Next task `mix conform.configure` generates `.conf` files for each app in respective config directory as well.

Now that's what I'm struggling to understand, please correct me if I'm wrong:
- conform is intended for use for built release and translate `.conf` into `sys.config` files according to rules in schema file
- schema and config files were generated for individual applications
- distillery is configured to produce single umbrella release which produces a single `sys.config` (with configs of 5 apps lumped together)

How do I generate single schema and single `.conf` file with this setup? and how does `conform` fits into this?

Thank you,
Alex

**Comment by coryodaniel** [comment]
I'm having the same issue using Conform 2.1.1 and Distillery 0.10.1. I found [another issue](https://github.com/bitwalker/distillery/issues/56) where it seems to be solved, but I could not get it to work either. My release VSN directory is missing the schema and conf files. See attached screen shots.

*distillery and conform non-umbrella*
<img width="306" alt="distillery and conform non-umbrella" src="https://cloud.githubusercontent.com/assets/11587/19840271/6103428c-9eaf-11e6-822d-42cf6e402630.png">

*distillery and conform umbrella*
<img width="333" alt="distillery and conform umbrella" src="https://cloud.githubusercontent.com/assets/11587/19840273/66ffceda-9eaf-11e6-9adb-e57d6c23b321.png">

**Comment by coryodaniel** [comment]
I have tried this with the master branches of conform and distillery and still have no luck.

**Comment by coryodaniel** [comment]
@akurkin you may want to hop over to [this ticket](https://github.com/bitwalker/distillery/issues/56) if you are experiencing issues!

**Comment by coryodaniel** [comment]
@akurkin Would you mind taking a peek at this PR to see if it solves your problem? ->

https://github.com/bitwalker/conform/pull/94

**Comment by akurkin** [comment]
@coryodaniel sure, I'm more than happy to try it out :) hopefully will get back to it this week. Does your change fixes the way mix tasks work or should I manually place schema files in apps?

**Comment by coryodaniel** [comment]
@akurkin changes the plugin that the release mix task uses. It'll grab each of the conform configs/schemas and merge them together to make one for the whole umbrella. It only ends up in the release since its generated.

**Comment by akurkin** [comment]
@coryodaniel I've tried last week, it turned out at a first glance that generated sys.config was in different format than in the one generated by distillery from master branch. I.e. it contained all files merged, but they were merged but not `flatten`. Too bad I didn't save the output file, I'm going to give a shot one more time and hopefully provide more useful info.

**Comment by bitwalker** [comment]
@akurkin Were you able to confirm if there was an issue?

**Comment by akurkin** [comment]
@bitwalker @coryodaniel today we've tried converting configs for all in-umbrella apps using latest conform and distillery releases, and all worked smoothly - merging configs into one (at `rel/<app>/var/sys.config`) and then starting an app, so I think this issue can be closed, thanks much for hard work on this, seems a really big step forward for making it easier to run and release elixir apps! 🙇 👏 🐝 

the next steps left for us to figure out how to put symlinks of .conf files into generated release, so that configuration can be separated from release (perhaps via plugin functionality in distillery?) - so please let me know if you have any thoughts, otherwise I think this issue can be closed

**Comment by bitwalker** [comment]
@akurkin You can simply use the `RELEASE_CONFIG_DIR` environment variable to have the release look in a different location for the configs - no need to symlink :)
